# ==============================
#   AlloyBERT Binary Classification (YS_Class)
# ==============================

# --- Training Setup ---
epochs: 20                 # sanity run first; bump to 20–50 after
batch_size: 4
stage: finetune
notes: "YS binary classification with AlloyBERT"
debug: false
load_pretrained: false

# --- Optimizer ---
optim:
  lr: 1.0e-5

# --- Scheduler ---
sch:
  name: linear
  warmup_steps: 0

# --- Paths ---
paths:
  train_data: 'data/newdataset/tr1.pkl'      # from your stratified split
  val_data:   'data/newdataset/vl1.pkl'
  tokenizer:  'roberta-base'
  pretrained: ''

# --- Task Type ---
task_type: classification
num_labels: 2
dropout: 0.1

# --- Dataset Columns ---
text_column: text
target_column: YS_Class

# --- Device ---
device: mps          # use 'cpu' if MPS not available

# --- Misc ---
seed: 42

# --- Dataloader Settings ---
dataloader:
  num_workers: 0
  pin_memory: false
